config/routes.rb
Rails.application.routes.draw do
  root to: "contacts#index"
  resources :contacts

  namespace :api do
    resources :contacts
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
# == Schema Information
#
# Table name: contacts
#
#  created_at :datetime         not null
#  email      :string
#  id         :bigint(8)        not null, primary key
#  name       :string
#  phone      :string
#  twitter    :string
#  updated_at :datetime         not null
#

class Contact < ApplicationRecord
end

app/controllers/api/application_controller.rb
class Api::ApplicationController < ApplicationController
  protect_from_forgery with: :null_session
end

app/controllers/api/contacts_controller.rb
class Api::ContactsController < Api::ApplicationController
  before_action :set_contact, only: %i[show edit update destroy]

  def index
    contacts = Contact.all
    render :json => contacts
  end

  def show
    render :json => @contact
  end

  def create
    contact = Contact.new(contact_params)

    if contact.save
      render :json => contact
    end
  end

  def update
    if @contact.update(contact_params)
      render :json => @contact
    end
  end

  def destroy
    @contact.destroy
    render :json => @contact
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_contact
    @contact = Contact.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def contact_params
    params.require(:contact).permit(:name, :email, :twitter, :phone)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[show edit update destroy]
  before_action :set_contact_count, only: %i[index show new edit]

  def index
    @contacts = Contact.all.order(:created_at)
    render :index_svelte
  end

  def show
  end

  def new
    @contact = Contact.new
  end

  def edit
  end

  def create
    @contact = Contact.new(contact_params)

    if @contact.save
      redirect_to @contact, notice: "Contact was successfully created."
    else
      render :new
    end
  end

  def update
    if @contact.update(contact_params)
      redirect_to @contact, notice: "Contact was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @contact.destroy
    redirect_to contacts_url, notice: "Contact was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_contact
    @contact = Contact.find(params[:id])
  end

  def set_contact_count
    @contact_count = Contact.all.count
  end

  # Only allow a trusted parameter "white list" through.
  def contact_params
    params.require(:contact).permit(:name, :email, :twitter, :phone)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def root
  end

  def counter
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # action name to use for the primary submit button on scaffold-created CRUD forms
  def btn_action_prefix
    case action_name
    when "new", "create"
      "Create"
    when "edit", "update"
      "Update"
    end
  end

  def alert_class(alert_type)
    alert_type = {
      alert: "danger",
      notice: "info",
    }.with_indifferent_access.fetch(alert_type, alert_type.to_s)
    "alert-#{alert_type}"
  end
end

app/views/contacts/_form.html.erb
<%= simple_form_for(contact) do |f| %>
 <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, autofocus: true %>
    <%= f.input :email %>
    <%= f.input :twitter %>
    <%= f.input :phone %>
  </div>

  <%= button_tag type: "submit", class: "btn btn-primary" do %>
    <%= "#{btn_action_prefix} Contact" %>
  <% end %>

  <%= link_to "Back", :back, class: "btn btn-secondary" %>
<% end %>

app/views/contacts/_header.erb
<div class="page-header">
  <div class="d-flex justify-content-between align-items-center">
    <h1><%= title %></h1>

    <%= svelte_component("ContactCount", message: "Count", count: local_assigns[:contact_count]) %>
  </div>
</div>

app/views/contacts/edit.html.erb
<%= render "header", title: "Editing Contact", count_label: "All", contact_count: @contact_count %>

<%= render "form", contact: @contact %>

app/views/contacts/index.html.erb
<%= render "header", title: "Contacts", count_label: "All", contact_count: @contact_count %>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Email</th>
      <th>Twitter</th>
      <th>Phone</th>
      <th>Actions
      </th>
    </tr>
  </thead>
  <tbody>
    <% @contacts.each do |contact| %>
    <tr>
      <td><%= link_to contact.id, contact_path(contact) %></td>
      <td><%= contact.name %></td>
      <td><%= contact.email %></td>
      <td><%= contact.twitter %></td>
      <td><%= contact.phone %></td>
      <td>
        <%= link_to "Edit", edit_contact_path(contact), class: "btn btn-primary btn-xs" %>
        <%= link_to "Destroy", contact_path(contact), 
            method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New Contact", new_contact_path, class: "btn btn-primary" %>

app/views/contacts/index_svelte.html.erb
<%= render "header", title: "Contacts", count_label: "Count" %>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Email</th>
      <th>Twitter</th>
      <th>Phone</th>
      <th>Actions
      </th>
    </tr>
  </thead>
   <%= svelte_component("ContactList", {contacts: @contacts}, tag: "tbody") %>
</table>

<%= svelte_component("NewContactButton") %>

app/views/contacts/new.html.erb
<%= render "header", title: "Create Contact", count_label: "All", contact_count: @contact_count %>

<%= render "form", contact: @contact %>

app/views/contacts/show.html.erb
<%= render "header", title: "Contact", count_label: "All", contact_count: @contact_count %>

<dl>
  <dt>Name</dt> <dd><%= @contact.name %></dd>
  <dt>Email</dt><dd><%= @contact.email %></dd>
  <dt>Twitter</dt><dd><%= @contact.twitter %></dd>
  <dt>Phone</dt><dd><%= @contact.phone %></dd>
</dl>

<%= link_to "Edit", edit_contact_path(@contact), class: "btn btn-primary" %>
<%= link_to "Back", contacts_path, class: "btn btn-secondary" %>

 <%= link_to "Destroy", contact_path(@contact),
      method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>

app/views/layouts/application.html.slim
doctype 5
html
  head
    title Svelte On Rails
    = stylesheet_link_tag    "application", media: "all", 'data-turbolinks-track': 'reload'
    = javascript_include_tag "application", 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag "application", 'data-turbolinks-track': 'reload'
    = javascript_pack_tag "application", 'data-turbolinks-track': 'reload'
    = csrf_meta_tag
    meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"

  body id=(controller.controller_name) class=(controller.action_name)
    header
      nav.navbar.navbar-expand-md.navbar-dark.fixed-top.bg-dark
        .container
          a.navbar-brand href="/" Svelte On Rails
          button.navbar-toggler type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
            span.navbar-toggler-icon

          #navbarSupportedContent.collapse.navbar-collapse
            ul.navbar-nav.ml-auto
              / - if current_user
              /   li.nav-item.dropdown
              /     a#dropdown.nav-link.dropdown-toggle data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"
              /       = current_user.email
              /
              /     .dropdown-menu aria-labelledby="dropdown"
              /       a.dropdown-item href="/" Sign Out
              / - else
              /   a.nav-link href="/" Sign In


    main.container role="main"
      - flash.each do |name, msg|
        .alert.alert-dismissable class=alert_class(name) role="alert"
          button.close type="button" data-dismiss="alert" aria-label="Close"
            span aria-hidden="true" &times;
          = raw(msg)
      = yield

    footer.footer
      .container
        p &copy; #{Date.current.year} All rights reserved.